<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GenesisSharp.Cpu68000\GenesisSharp.Cpu68000.csproj" />
    <ProjectReference Include="..\GenesisSharp.CpuZ80\GenesisSharp.CpuZ80.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
