<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GenesisSharp.Cpu68000\GenesisSharp.Cpu68000.csproj" />
    <ProjectReference Include="..\..\src\GenesisSharp.CpuZ80\GenesisSharp.CpuZ80.csproj" />
    <ProjectReference Include="..\..\src\GenesisSharp.CpuSh2\GenesisSharp.CpuSh2.csproj" />
    <ProjectReference Include="..\..\src\GenesisSharp.Core\GenesisSharp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestRoms\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
